SELECT COLABORADORES.NOME_COLABORADOR, LOCAL_DE_TRABALHO.UF, SUM(SALARIOS.VALOR_PAGO) FROM SALARIOS INNER JOIN COLABORADORES
	ON (SALARIOS.ID_COLABORADOR = COLABORADORES.ID_COLABORADOR) 
	INNER JOIN LOCAL_DE_TRABALHO
	ON (LOCAL_DE_TRABALHO.ID_COLABORADOR = COLABORADORES.ID_COLABORADOR) 
WHERE 
	date_part('year', SALARIOS.DATA_PAGAMENTO) = 2014
GROUP BY
	COLABORADORES.NOME_COLABORADOR, LOCAL_DE_TRABALHO.UF
